### ISSUE TITLE
Getting Error after install your extension 

### ISSUE THREAD

**Issue by mrmoyeez** [CreDevLabz/magento2-testimonials#2]
Fatal error:  Interface 'Credevlabz\Testimonials\A
pi\Data\TestimonialInterface' not found in /home/245255.cloudwaysapps.com/kabzgkrtyz/public_html/app/code/CreDevLab/magento2-testimonials-ma
ster/Model/Testimonial.php on line 14                   

I am using Magento 2.26 and cloudways hosting . Could you help me on this issue ??

**Comment by amansrivastava** [comment]
It was abandoned for a longtime now, I'll make it working soon.

**Comment by amansrivastava** [comment]
Hi @mrmoyeez,
code is updated now, you can try installation using new code.
Closing this ticket.
